### ISSUE TITLE
Different bit depth - different output

### ISSUE THREAD

**Issue by TbtBI** [pinterf/AddGrainC#1]
Hi,
when using different bit depth the output is different. Here a test:
```
Colorbars(pixel_type="yv12")
# ConvertBits(16)
# ConvertBits(32)
addgrain(800, seed=0)
```
The result - http://imgbox.com/g/NvXjNELXPG
1.8.0 and 1.8.1 both have that behavior.

Tested with the version from here - https://forum.doom9.org/showthread.php?p=1905669#post1905669 and the output is same for all bit depths ( http://imgbox.com/g/siBCP4BD3o ).

**Comment by pinterf** [comment]
Thanks for the report. Please try 1.8.2

**Comment by TbtBI** [comment]
Thanks, it's ok.
