### ISSUE TITLE
Support AVX2, AVX512

### ISSUE THREAD

**Issue by kedaitinh12** [pinterf/AddGrainC#3]
I seen Holywu support avx2, avx512 now in vapoursynth-addgrain, can you back port it to avisynth??? 
https://github.com/HomeOfVapourSynthEvolution/VapourSynth-AddGrain/commit/75782b63fd939714aa828dc0ca3b1033f9691f5c

**Comment by pinterf** [comment]
I'm aware of it, thanks. As you can see (or not) AddGrainC was once already backported, after than VS got these changes including a whole vectorclass. I'm not planning to backport it again.
You could make some real-world benchmarks for sse4.1 vs. avx2 vs. avx512 using the VapourSynth version how scripts benefit from a change.
It is also not necessary in the future to inform me when other projects on the internet have e.g. avx512 but mine have not.
